version: '3.3'
networks:
  my-store:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5430:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      my-store:
        ipv4_address: 172.18.0.2

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    networks:
      my-store:
        ipv4_address: 172.18.0.3

  # mysql:
  #   image: mysql:5
  #   environment:
  #     - MYSQL_DATABASE=my_store
  #     - MYSQL_USER=root
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - MYSQL_PORT=3306
  #   ports:
  #     - 3305:3306
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   networks:
  #     my-store:
  #       ipv4_address: 172.18.0.4

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - PMA_HOST=root
  #   ports:
  #     - 8080:80
  #   networks:
  #     my-store:
  #       ipv4_address: 172.18.0.5
