version: '3.3'
networks:
  my-store:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5430:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      my-store:
        ipv4_address: 172.18.0.2

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    networks:
      my-store:
        ipv4_address: 172.18.0.3


  # node:
  #   image: node
  #   # working_dir: ./
  #   environment:
  #     - NODE_ENV=production
  #   # volumes:
  #   #   - ./
  #   # expose:
  #   #   - "8081"
  #   # ports: # use if it is necessary to expose the container to the host machine
  #   #   - "8001:8001"
  #   command: "npm run dev"


#Configuracion de pgadmin desde consola que si funciono
# docker run -p 5050:80 \
#     -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \
#     -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
#     -d dpage/pgadmin4


#Encontrar la IP de un Docker
# docker inspect \
#   -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id
